### ISSUE TITLE
Make downloading parity more robust

### ISSUE THREAD

**Issue by amaurymartiny** [parity-js/light#17]
Right now we just try to fetch parity once: https://github.com/parity-js/light/blob/20679c4515cf18570ab751c19c28c2e295854d0a/electron/operations/fetchParity.js#L53-L61

And somtimes we have errors:
![download](https://user-images.githubusercontent.com/1293565/40170356-7ba48b16-59c8-11e8-9c2c-c2e991946b6e.png)

It'd be nice to:
- Retry 2-3 times if the 1st time fails (and show a Check Network Connection message if failing after 3 times)
- Check that the checksum is correct after downloading (or re-download if not)

**Comment by 5chdn** [comment]
Why is it downloading parity at all. I have it installed. I even had it running. It should check that first if possible.

**Comment by amaurymartiny** [comment]
The download parity logic needs to be there anyways, for users who's 1st experience with parity is the Light Wallet.

Next steps to add:
- if parity is already installed in a standard location (program files, /usr/bin etc) or is in PATH, then don't install
- if not, then install it (whether or not it is already running)

Even if parity is running (but from a non-standard location), I think we should be downloading it, so that the next time the user double-clicks on the Light Wallet it'll run parity immediately.
