### ISSUE TITLE
Import Account

### ISSUE THREAD

**Issue by amaurymartiny** [parity-js/light#20]
For now there's a Create Account mechanism, but there should also be an Import Account one.

The process should be simpler:
- user inputs his 12-word phrase
- user chooses a password
- confirm

**Comment by brianflanagan** [comment]
Perhaps a little text below step 1 of create account that says something like 'Already have an account? Import account'.

**Comment by amaurymartiny** [comment]
Sounds good, I'll work on a 1st version.
