### ISSUE TITLE
Shows incorrect ETH balance after switching account

### ISSUE THREAD

**Issue by bjornwgnr** [parity-js/light#37]
The wallet shows the balance of the previous account after switching to a new account.

**Comment by amaurymartiny** [comment]
When switching accounts, the cached (previous value) is indeed shown.

@brianflanagan's idea was to show gray placeholders, like facebook loading cards.

E.g. this library https://github.com/danilowoz/react-content-loader

**Comment by bjornwgnr** [comment]
Same counts for the accounts identicon+name in the top.

<img width="385" alt="screen shot 2018-06-13 at 22 19 17" src="https://user-images.githubusercontent.com/17831185/41375948-e5a4899a-6f57-11e8-92b1-c79da79f8162.png">
