### ISSUE TITLE
Account view

### ISSUE THREAD

**Issue by bjornwgnr** [parity-js/light#39]
Personally, I think I'd prefer if the identicon was shown in the 'top bar' next to the account name if you can make that work with the current design.

<img width="359" alt="screen shot 2018-06-11 at 19 01 55" src="https://user-images.githubusercontent.com/17831185/41248789-f0d16d60-6da9-11e8-8fc5-409bd332a4f8.png">

The information provided in the following view seems fairly redundant. It shows both the acc name and address twice. Furthermore, instead of having a dedicated 'copy address to clipboard'-button, this functionality could be provided through a click on the text box plus a dialog that states that the address was copied to the clipboard. 

<img width="352" alt="screen shot 2018-06-11 at 19 00 25" src="https://user-images.githubusercontent.com/17831185/41248711-bbf285ac-6da9-11e8-9ef4-4e1258b7a136.png">

**Comment by amaurymartiny** [comment]
Agreed and agreed.
