### ISSUE TITLE
"+" button in account overview view doesn't work

### ISSUE THREAD

**Issue by bjornwgnr** [parity-js/light#40]
After clicking on the "+" button:

<img width="605" alt="screen shot 2018-06-11 at 19 23 17" src="https://user-images.githubusercontent.com/17831185/41249781-f05e422e-6dac-11e8-976f-e45dba71b62d.png">

**Comment by bjornwgnr** [comment]
Just restarted it, now it works.

**Comment by amaurymartiny** [comment]
Noted, if you happen to reproduce this again, could you do CMD+Alt+I in the Electron app, this will show the console, and paste here all the logs
