### ISSUE TITLE
"confirm transaction" button not working?

### ISSUE THREAD

**Issue by Tbaut** [parity-js/light#45]
I'm on Kovan (light node launched before `yarn electron`)
Select an account> type a receiver's address, click on "send"> type my password> click on "confirm transaction"

![image](https://user-images.githubusercontent.com/33178835/41364132-0dbcbb72-6f36-11e8-96dc-22a84d1655ae.png)

No error in electron console, no call fired in network tab, no transaction mined in parity console. As if the button was not doing anything.

**Comment by Tbaut** [comment]
fixed in the latest release!

**Comment by amaurymartiny** [comment]
Happened to me too. It happens when the light node is in not-responding mode.

I added a loading state on the button, so that when you click once, it gets greyed out.
