### ISSUE TITLE
Whitelisting of Tokens

### ISSUE THREAD

**Issue by amaurymartiny** [parity-js/light#6]
A feature/bug requested in the old Parity was that instead of fetching automatically all the tokens a particular account has, the user whitelists the tokens he wants to be shown on the main page.

In particular, there needs to be a page where the user chooses to Add Token (a bit like MM), with the following fields:
- Token address
- Token name
- Token symbol
- Token image (url is enough for now, no need for image uploading)

We could also keep a small database of the most popular tokens ourselves, like MyCrypto does.

(Lower priority, let's focus on sending/receiving Ether first).

**Comment by brianflanagan** [comment]
I think keeping a small (or large) database and autocompleting via token name or symbol would be the most user friendly for _most_ users.

**Comment by 5chdn** [comment]
> We could also keep a small database of the most popular tokens ourselves, like MyCrypto does.

We could even use the mycrypto database, it's on github afaik

**Comment by amaurymartiny** [comment]
Yes, excellent idea, I don't want to maintain a separate database of tokens.

Do you have a link to mycrypto's db? In particular i want to check if they have token images, which they don't show in the UI.

@5chdn, all other things being equal, which db do you is more maintainted/up-to-date?

In general, I'd prefer having a local file / in-memory tokens db, UX-wise there wouldn't need to be a network fetch to fetch token metadata.

**Comment by 5chdn** [comment]
I think they use https://github.com/ethereum-lists/tokens/
