### ISSUE TITLE
Add error message when wrong password

### ISSUE THREAD

**Issue by Tbaut** [parity-js/light#68]
Add an error message when the wrong password is typed in.
There is nothing apart from a console error right now.

A red "wrong password" in place of the confirmed transaction button would do the trick. (removing it as soon as the user types in the pwd field)

**Comment by Verrien** [comment]
@Tbaut Pretty sure that this still persists in Beta 0.3.0 Needs retesting.

**Comment by Tbaut** [comment]
@Verrien this issue is super old and the software looked different when I logged (and we closed) it. Please open a new issue if you have a similar problem in the latest versions.
